-- LISTS ALL RECORDS WITH A SCORE >= 10 IN THE TABLE SECOND_TABLE OF THE DATABASE HBTN_0C_0
-- COMMAND TOL LISTS THE BEST SCORE
SELECT score,name FROM second_table WHERE score >= 10  ORDER BY score DESC;