--  LISTS ALL RECORDS OF THE TABLE SECOND_TABLE OF THE DATABASE HBTN_0C_0f
-- COMMAND TO LISTS ALL RECORDS OF THE TABLE SECOND_TABLE
SELECT score, name FROM second_table WHERE name IS NOT NULL ORDER BY score DESC;